using System.Text.Json.Serialization;
using RadarrMcp.Models;

namespace RadarrMcp.Models;

/// <summary>Source-generated JSON serializer context for all Radarr models.</summary>
[JsonSerializable(typeof(RadarrMovie))]
[JsonSerializable(typeof(List<RadarrMovie>))]
[JsonSerializable(typeof(RadarrLookupResult))]
[JsonSerializable(typeof(List<RadarrLookupResult>))]
[JsonSerializable(typeof(RadarrQualityProfile))]
[JsonSerializable(typeof(List<RadarrQualityProfile>))]
[JsonSerializable(typeof(RadarrUnmappedFolderItem))]
[JsonSerializable(typeof(List<RadarrUnmappedFolderItem>))]
[JsonSerializable(typeof(RadarrRootFolder))]
[JsonSerializable(typeof(List<RadarrRootFolder>))]
[JsonSerializable(typeof(RadarrQueueResponse))]
[JsonSerializable(typeof(RadarrQueueRecord))]
[JsonSerializable(typeof(List<RadarrQueueRecord>))]
[JsonSerializable(typeof(RadarrSystemStatus))]
[JsonSerializable(typeof(RadarrHealthCheck))]
[JsonSerializable(typeof(List<RadarrHealthCheck>))]
[JsonSerializable(typeof(MovieSearchResult))]
[JsonSerializable(typeof(List<MovieSearchResult>))]
[JsonSerializable(typeof(LibraryMovie))]
[JsonSerializable(typeof(List<LibraryMovie>))]
[JsonSerializable(typeof(AddMovieResult))]
[JsonSerializable(typeof(List<AddMovieResult>))]
[JsonSerializable(typeof(QueueItem))]
[JsonSerializable(typeof(List<QueueItem>))]
[JsonSerializable(typeof(SystemStatusResponse))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(MultiUpdateRequest))]
[JsonSerializable(typeof(List<MultiUpdateRequest>))]
[JsonSerializable(typeof(MultiUpdateResult))]
[JsonSerializable(typeof(List<MultiUpdateResult>))]
[JsonSerializable(typeof(MultiSearchRequest))]
[JsonSerializable(typeof(List<MultiSearchRequest>))]
[JsonSerializable(typeof(MultiSearchResult))]
[JsonSerializable(typeof(List<MultiSearchResult>))]
[JsonSerializable(typeof(MultiGetDetailsResult))]
[JsonSerializable(typeof(List<MultiGetDetailsResult>))]
[JsonSerializable(typeof(RootFolderInfo))]
[JsonSerializable(typeof(List<RootFolderInfo>))]
[JsonSerializable(typeof(UnmappedFolderInfo))]
[JsonSerializable(typeof(List<UnmappedFolderInfo>))]
[JsonSerializable(typeof(UnmappedFoldersResult))]
[JsonSerializable(typeof(ImportMovieRequest))]
[JsonSerializable(typeof(List<ImportMovieRequest>))]
[JsonSerializable(typeof(ImportMovieResult))]
[JsonSerializable(typeof(List<ImportMovieResult>))]
[JsonSerializable(typeof(List<int>))]
[JsonSerializable(typeof(RadarrCommandResponse))]
[JsonSerializable(typeof(RadarrWantedCutoffResponse))]
[JsonSerializable(typeof(CutoffUnmetMovie))]
[JsonSerializable(typeof(List<CutoffUnmetMovie>))]
[JsonSourceGenerationOptions(
    PropertyNameCaseInsensitive = true,
    WriteIndented = false,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
public sealed partial class RadarrJsonContext : JsonSerializerContext { }
